### ISSUE TITLE
Pycopg2 & GCC issues since update

### ISSUE THREAD

**Issue by rawrxiv** [binhex/arch-pycharm#1]
Hey Binhex, appreciate the images. 

After updating the image from the dash in unraid one of my venvs glitched and I had to rebuild it but got some pip errors when install modules regex and psycopg2.

regex is failing due to GCC missing. 
psycopg2 is failing due to missing pg_config.

**Comment by binhex** [comment]
ok so regex module is failing due to missing gcc, so i will need to add in gcc for this to install.
psycopg2 installed fine without a hitch for me on a clean python 2.7 venv.

**Comment by rawrxiv** [comment]
Awesome  thank you, try a 3.7 venv. Might need python3-dev installed possibly.

**Comment by binhex** [comment]
psycopg2 installs for both python 2.x and 3.x using venv, no issues for me :-).

new image is now built which now includes gcc, so that will fix up 'regex' module.
