### ISSUE TITLE
Sudo Password?

### ISSUE THREAD

**Issue by neelybd** [binhex/arch-pycharm#4]
I have been trying to install ta-lib using the pycharm terminal, but this requires sudo permissions. I have tried the standard passwords such as root, blank, and password.

What is the root password so that I can either use sudo or su?

![image](https://user-images.githubusercontent.com/34224624/110074487-2527bf80-7d36-11eb-9a55-7f6dc7198313.png)

**Comment by binhex** [comment]
simple solution use ```docker exec -it <container name> bash``` that way you are running as root, or if you really want to use sudo then docker exec in and then set password for user nobody.

**Comment by neelybd** [comment]
That did it. Thank you, I'm new to docker and your images are the best I've seen.
