### ISSUE TITLE
No JDK Found

### ISSUE THREAD

**Issue by neelybd** [binhex/arch-pycharm#6]
Today, all of a sudden, all of my docker containers with pycharm stopped working and wont reload. The error in the log is below.

2021-04-05 21:45:32,370 DEBG 'start' stdout output:
ERROR: Cannot start PyCharm

No JDK found. Please validate either PYCHARM_JDK, JDK_HOME or JAVA_HOME environment variable points to valid JDK installation.

I have tried to install jdk within the docker container, but I can't run pacman because of a alpm error.

**Comment by binhex** [comment]
See Q10 from the following link for the solution:- https://github.com/binhex/documentation/blob/master/docker/faq/general.md
