### ISSUE TITLE
VNC passwd file location is incorrect

### ISSUE THREAD

**Issue by volcanihpc** [binhex/arch-pycharm#7]
Hello,

The ```/usr/local/bin/start.sh```  script is setting the VNC password file location in: 
```~/.vnc/passwd```

However, ```vncpasswd``` is saving the password file in:
```~/.config/tigervnc/passwd```

Thus making it impossible to login, and receiving this error:

> Authentication failure: No password configured for VNC Auth

**Comment by binhex** [comment]
Thanks for the issue, and yep you are right, looks like the path has changed this did work!. This image is built from an intermediate image so i have committed the change there and will be subsequent images shortly, including this one.

For ref:- https://github.com/binhex/arch-int-gui/commit/94a7b4d19647531a0834a240f03a8998be4f1086
